### ISSUE TITLE
不会被封号的最快速度，参数怎么选择？

### ISSUE THREAD

**Issue by oneforcat** [Cyenoch/zjy2.icve#1]

**Comment by oneforcat** [comment]
目前测试非默认参数，很容易封号30秒

**Comment by Cyenoch** [comment]
我又被封了一个半小时，被封的原因是发布了留言，建议关闭

如果被解禁了之后短时间内再刷，videoIncrementBase+videoIncrementX 要低于10不然马上又被封..

**Comment by oneforcat** [comment]
我现在关闭了评论和笔记，四项参数分别是1 5 20 5，没有封号

**Comment by Cyenoch** [comment]
那就行

**Comment by oneforcat** [comment]
这个怎么一次指定多个课程，顺序完成呀

**Comment by Cyenoch** [comment]
多个课程还没弄，稍等下

**Comment by Cyenoch** [comment]
弄完了，我号被封了没法去试，你自行尝试...

**Comment by oneforcat** [comment]
有个问题就是，选择多门课程，刷完第一门之后，会再次要求输入需要刷的模块（且仍是当前课程，需要先返回，再进入下一课程的模块选择），就失去了选择多门课的意义了

**Comment by Cyenoch** [comment]
明白了，稍等

**Comment by oneforcat** [comment]
我在模块函数里加了这个，解决了：
cishu=2 #全局变量
 global cishu 
    if cishu%2 == 0:
        i = int(len(processList) + 2)
        cishu+=1
    else:
        i = int(len(processList) + 3)
        cishu += 1
第一次运行会刷课，第二次会返回，并且进入下一课程的模块选择

**Comment by Cyenoch** [comment]
我弄好了 ，submitNote我默认打开了你记得关一下，videoIncrementBase我也调了记得改一下

**Comment by oneforcat** [comment]
我们课程里面有一种课件是（其他）类型，目前这个py程序刷不了，但是只需要点进去再出来就是100%了，这个可以添加一下吗

**Comment by oneforcat** [comment]
对了对了，还有音频类型

**Comment by oneforcat** [comment]
上面这个问题，已经解决了，我在判定课件类型那儿加了，‘视频’ or ‘音频’，‘压缩包’ or ‘其他’

**Comment by oneforcat** [comment]
出现报错
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by oneforcat** [comment]
auth会发生改变，登录状态就失效了，可不可以改成号密模拟登录呀

**Comment by Cyenoch** [comment]
> auth会发生改变，登录状态就失效了，可不可以改成号密模拟登录呀

登录要验证码，很难搞

**Comment by oneforcat** [comment]
登录验证码可以手输，也可以对接个人工智能打码的

**Comment by oneforcat** [comment]
> > auth会发生改变，登录状态就失效了，可不可以改成号密模拟登录呀
> 
> 登录要验证码，很难搞
可以参考下这个
https://github.com/LycmSky/zjy

**Comment by Cyenoch** [comment]
无精力..

**Comment by oneforcat** [comment]
> 无精力..

好叭好叭
