### ISSUE TITLE
视频{'code': 1}任务结果显示完成，实际未观看

### ISSUE THREAD

**Issue by KawaUso-Jyou** [Cyenoch/zjy2.icve#3]
![Snipaste_2021-04-11_16-29-57](https://user-images.githubusercontent.com/53994160/114297484-7b311500-9ae3-11eb-87fb-9e0084abbd83.png)
![Snipaste_2021-04-11_16-33-11](https://user-images.githubusercontent.com/53994160/114297514-a6b3ff80-9ae3-11eb-95fd-42cfaddde9fe.png)

所有视频均这样提示

**Comment by Cyenoch** [comment]
这个视频的视频长度是多少

**Comment by Cyenoch** [comment]
顺便试试最新的脚本，看看还有问题吗

**Comment by KawaUso-Jyou** [comment]
> 这个视频的视频长度是多少

不到10分钟

**Comment by KawaUso-Jyou** [comment]
> 顺便试试最新的脚本，看看还有问题吗

![Snipaste_2021-04-11_17-17-25](https://user-images.githubusercontent.com/53994160/114298830-d9152b00-9aea-11eb-8402-17063978efdc.png)
出现这种错误了

**Comment by Cyenoch** [comment]
那我也不知道是什么情况了...我这边正常

**Comment by KawaUso-Jyou** [comment]
> 那我也不知道是什么情况了...我这边正常

好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？

**Comment by Cyenoch** [comment]
> > 那我也不知道是什么情况了...我这边正常
> 
> 好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？

不清楚....

**Comment by KawaUso-Jyou** [comment]
> > > 那我也不知道是什么情况了...我这边正常
> > 
> > 
> > 好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？
> 
> 不清楚....

不对，不是课件有时长为零的视频，而是观看时长进度为零。
刚才我测试了一下，当用脚本刷一个从未观看过的视频（也就是观看视频进度为0）时，脚本必报错；
当手动把一个从未观看过的视频观看一段时间（也就是使视频观看进度时长不为0）时，可以用脚本顺利刷这个视频。

**Comment by KawaUso-Jyou** [comment]
> > > 那我也不知道是什么情况了...我这边正常
> > 
> > 
> > 好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？
> 
> 不清楚....

![Snipaste_2021-04-11_19-39-45](https://user-images.githubusercontent.com/53994160/114302887-bdffe680-9afd-11eb-984c-9df5666930a6.png)
当时还会遇到另一个问题，刷完这个视频后不会继续下一个……（wwwwwwwwwwwwwwww

**Comment by Cyenoch** [comment]
> > > > 那我也不知道是什么情况了...我这边正常
> > > 
> > > 
> > > 好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？
> > 
> > 
> > 不清楚....
> 
> ![Snipaste_2021-04-11_19-39-45](https://user-images.githubusercontent.com/53994160/114302887-bdffe680-9afd-11eb-984c-9df5666930a6.png)
> 当时还会遇到另一个问题，刷完这个视频后不会继续下一个……（wwwwwwwwwwwwwwww

脚本我撤回了更改，对于这个问题你再试试

**Comment by Cyenoch** [comment]
> > > > 那我也不知道是什么情况了...我这边正常
> > > 
> > > 
> > > 好像是`p=(inc/audioVideoLong) * 100`中`audioVideoLong`为0了？难道是我的课件里面有时长为零的视频？
> > 
> > 
> > 不清楚....
> 
> 不对，不是课件有时长为零的视频，而是观看时长进度为零。
> 刚才我测试了一下，当用脚本刷一个从未观看过的视频（也就是观看视频进度为0）时，脚本必报错；
> 当手动把一个从未观看过的视频观看一段时间（也就是使视频观看进度时长不为0）时，可以用脚本顺利刷这个视频。

你自行调试下，我复现不了所以查不了原因
