### ISSUE TITLE
刷全部模块doneCellVideo方法死循环，视频一直都是100%

### ISSUE THREAD

**Issue by ximux** [Cyenoch/zjy2.icve#5]
while (inc < audioVideoLong):条件<=改为<就好，其他的没用过暂未发现问题

**Comment by Cyenoch** [comment]
目前是这样的

https://github.com/Cyenoch/zjy2.icve/blob/022f993ded435531594bb41c8f6e93158a6f94e2/icve.py#L316

**Comment by wangjunjie514** [comment]
音频的无法

**Comment by Cyenoch** [comment]
> 音频的无法

没做 有缘再做

**Comment by wangjunjie514** [comment]
555555555 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月22日(星期二) 晚上8:58
***@***.***&gt;;
抄送:&nbsp;&quot;wangjunjie514&quot;<2545964862@***@***.***&gt;;
主题:&nbsp;Re: [Cyenoch/zjy2.icve] 刷全部模块doneCellVideo方法死循环，视频一直都是100% (#5)
